## COnfiguration of board. Note that 0,0 is first position (upper left)
# First coordinate is the column second is the row

board_size: [8,5]
board_size_mm: [312,195]
board_config:
  '0,0': ['yellow', 'square', False]
  '1,0': ['green', 'hexagon', False]
  '2,0': ['yellow', 'circle', True]
  '3,0': ['blue', 'trapezoid', True]
  '4,0': ['green', 'triangle', False]
  '5,0': ['red', 'hexagon', False]
  '6,0': ['blue', 'square', True]
  '7,0': ['red', 'circle', False]

  '0,1': ['green', 'circle', True]
  '1,1': ['blue', 'hexagon', True]
  '2,1': ['red', 'triangle', False]
  '3,1': ['yellow', 'hexagon', True]
  '4,1': ['red', 'square', True]
  '5,1': ['yellow', 'circle', False]
  '6,1': ['green', 'trapezoid', False]
  '7,1': ['yellow', 'triangle', False]

  '0,2': ['red', 'trapezoid', True]
  '1,2': ['yellow', 'triangle', True]
  '2,2': ['green', 'square', True]
  '3,2': ['blue', 'hexagon', False]
  '4,2': ['green', 'triangle', True]
  '5,2': ['blue', 'trapezoid', True]
  '6,2': ['red', 'hexagon', False]
  '7,2': ['blue', 'square', True]

  '0,3': ['yellow', 'hexagon', False]
  '1,3': ['green', 'square', False]
  '2,3': ['blue', 'circle', True]
  '3,3': ['red', 'square', True]
  '4,3': ['yellow', 'trapezoid', False]
  '5,3': ['green', 'hexagon', True]
  '6,3': ['yellow', 'square', True]
  '7,3': ['green', 'trapezoid', True]

  '0,4': ['blue', 'triangle', True]
  '1,4': ['red', 'circle', True]
  '2,4': ['yellow', 'trapezoid', True]
  '3,4': ['green', 'circle', False]
  '4,4': ['blue', 'triangle', False]
  '5,4': ['red', 'trapezoid', True]
  '6,4': ['blue', 'circle', False]
  '7,4': ['red', 'triangle', True]